### ISSUE TITLE
Hide GUI

### ISSUE THREAD

**Issue by BkMak16** [RosettaDrone/rosettadrone#13]
Would be great to be able to hide the gui to have an uninterrupted almost cinematic view of the flight. 

Perhaps a button to hide and a screen tap anywhere to unhide. 

If anyone can think of a quick and easy way to do this in the mean time. Would be interested to give it a try. I've considered setting the current icons to empty .png to achieve this for example. 
 I'm sure at some point this feature will come out when there's a meaningful need to push an update. 

This is a great project so far.

**Comment by The1only** [comment]
Just comment out what you do not need in the activity_gui.xml file and then compile, you will get some errors, but just comment out the lines that fail, and go. You can also make two activity_gui.xml files and select one of them by configuration. This is not something I will add to the main tree unless there are more demands. 

Terje
