### ISSUE TITLE
When running RosettaDrone II from Mavlink, and then using the remote controller to switch to a different mode, the software looses connection.

### ISSUE THREAD

**Issue by The1only** [RosettaDrone/rosettadrone#16]
When flying from Mavlink, using Dronekit etc. and then the operator tries to take over using the remote controller sticks, nothing happens, when the user then changes the mode to be able to do a manual takeover, the Rosetta drone must be restarted to be able to control the drone again. Seems to be a mode/connection issue...

**Comment by The1only** [comment]
Normally the drone is in GPS ATTI mode when using the Mavlink the drone enters JOYSTICK mode, and the RC joysticks are disabled when the mode switch is operated the drone jumps back to GPS ATTI mode, but now never reenters JOYSTICK mode !!!!!

**Comment by BkMak16** [comment]
Yes. You'll have to restart the drone and controller to get into joystick mode again.

Joystick mode only happens on the first run.

**Comment by The1only** [comment]
It’s fixed just not checked inn yet

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by BkMak16** [comment]
Nice one!

**Comment by The1only** [comment]
I am working with absolute positioning and missions now, will putt all when it works.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by The1only** [comment]
This should now be fixed in the latest master code.

**Comment by BkMak16** [comment]
Awesome!
