### ISSUE TITLE
Garbled Video in Rosetta app with DJI Phantom 4 V2 Pro and Pixel 2. Also no video to QGroundControl.

### ISSUE THREAD

**Issue by sequoia-hope** [RosettaDrone/rosettadrone#17]
**Describe the bug**

Hello!
I just compiled the app and loaded it on to a new Google Pixel 2. I have a telemetry connection and everything looks connected, but the video display is garbled. What is interesting is that sometimes I can see some parts of the image, but it is mostly garbled. See screenshot below.

**To Reproduce**
1. Compile the latest release.
2. Load on to a google pixel 2
3. connect to aircraft

**Expected behavior**
I expect to see video from the camera.

**Screenshots**
(Note that the screenshot was taken after the aircraft was disconnected, but the garbled video feed stayed onscreen after disconnecting, so this is what I was seeing.)
![Screenshot_20200806-235645](https://user-images.githubusercontent.com/1310634/89607822-466c1000-d828-11ea-91ec-914a293ae58d.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android 10

**Additional context**
I am able to send telemetry to QGroundControl but it just says "Waiting for video." Also on QGroundControl I can pick UDP h264 or UDP h265 for the video stream. Which is correct?

Thank you!

**Comment by The1only** [comment]
Ahh never tested Phantom 4 V2, if it uses the old video format, like the dji Air, some people have made a trick in the video transkoder function. For the new systems like Mavic 2 Pro and Martice 210 V2 there is a new video format, this works. 

Unfortunatly I have no Phantoms so I got to put thrust in you guys. The problem is with with the transkoding, and nails.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by The1only** [comment]
Try adding Phantom4 to the list og  of None Ocusync2 in MainActivity. Line 721 if I remember right...

**Comment by sequoia-hope** [comment]
Oh interesting. I have moved on from DJI to an open source drone, but if I dust this off again I will try it. Thank you!

**Comment by kripper** [comment]
Added
