### ISSUE TITLE
Are you already check last sdk and support for mavic mini ?

### ISSUE THREAD

**Issue by virtualrobotix** [RosettaDrone/rosettadrone#18]
Could nice that rosetta 2 can support mavic mini with last revision of sdk.
I havee one and i can support in test and implementation.
Some guys already test it ?
Best
Roberto

**Comment by The1only** [comment]
I’ll se if I can implement the latest SDK this week. I am always a bit afraid for what DJI have changed / removed, so I might bransh it out at first.

The latest SmartController fw misses USB RNDIS ant that do create issues for our software, wlan is slower.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by The1only** [comment]
I tried to upgrade the SDK, but there are issues and the code will not run, there are also several updates needed on Android libs, and Gradel... That all creates issues...  I am spending my time on getting goto position and mission-plan to work. 
We need more people !!!

**Comment by virtualrobotix** [comment]
If you tell me how i can help to support the project i can try , do you have some update ? Are your work share on git ? I find last update at 4 jul .

**Comment by The1only** [comment]
The project is now updated to SDK4.13 and working. This should support Mavic MINI, however NOT tested...

**Comment by virtualrobotix** [comment]
Great news i done some test today and update you.

**Comment by The1only** [comment]
Seems Mini does Not use OcuSync, that might be a problem for video. I am currently working on the compatibility issu with the non OcuSync systems. I expect a beta fix within a week.

**Comment by lukelu520** [comment]
@The1only thanks for your effort on mavic mini. We tested on mini today but its video stream doesn't show up in rosetta dron app. There is a message says "Image Transmission Signal Weak". We were wondering if you've updated the compatibility issue with the non-OcuSync systems. If so, is it in master or VIDEO_WORK branch ? Or video only works by using command line with QGC as mentioned in #23 ?

If you are too busy to work on it, hope you could point us a direction to work on the issue, then we'll start helping on the issue.

Thanks,
-- Luke

**Comment by The1only** [comment]
In the MainActivity is a list of drones that needs the old handling. Try adding non working drones and retest.

**Comment by avncalst** [comment]
I compiled the master branch yesterday and did a 1st test on mavic mini. First test looks promising. Congrats.

**Comment by avncalst** [comment]
Weird observation: using gstreamer code to receive the video stream from my mavic mini is unsuccessful. Most of the time gray screens due to unsuccessful decoding by my old Ubuntu pc. However when I use the video tab on my QGC station (v4.0.6) I get a perfect reception of the video stream with low latency. Any ideas?
![Screenshot from 2021-04-08 16-55-07_rev](https://user-images.githubusercontent.com/13418617/114051757-aae6df80-988d-11eb-9e1c-4362b88a2f85.png)

**Comment by The1only** [comment]
Software performance issue.
You need gStreamer with GPU support, and very efficient code.

**Comment by avncalst** [comment]
Thx

**Comment by avncalst** [comment]
I am currently testing my mavic mini using python code. Most of the features work, however the mini does not respond to the mavlink command "send_local_ned_velocity(vx, vy, vz)". Please advise. Thanks in advance.

**Comment by avncalst** [comment]
Please find hereafter some of the mavlink messages captured by logcat in response of python dronekit commands:

MOVING COMMAND + RESPONSE: mini does not really move but drifts somewhat.
MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED - sysid:255 compid:0 time_boot_ms:0 x:0.0 y:0.0 z:0.0 vx:0.0 vy:-2.0 vz:0.0 afx:0.0 afy:0.0 afz:0.0 yaw:0.0 yaw_rate:0.0 type_mask:4039 target_system:1 target_component:0 coordinate_frame:9
Message: MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED - sysid:255 compid:0 time_boot_ms:0 x:0.0 y:0.0 z:0.0 vx:0.0 vy:-2.0 vz:0.0 afx:0.0 afy:0.0 afz:0.0 yaw:0.0 yaw_rate:0.0 type_mask:4039 target_system:1 target_component:0 coordinate_frame:9

LANDING COMMAND: works correctly.
MAVLINK_MSG_ID_SET_MODE - sysid:255 compid:0 custom_mode:9 target_system:1 base_mode:1
Message: MAVLINK_MSG_ID_SET_MODE - sysid:255 compid:0 custom_mode:9 target_system:1 base_mode:1
MAVLINK_MSG_ID_SET_MODE: 9

**Comment by avncalst** [comment]
Issue solved: "send_local_ned_velocity(vx, vy, vz)" does not work. This message is interpreted as a set position -> the message to be sent is (different type_mask and position coordinates used) : 

def goto_position_target_local_ned(north, east, down):
    """
    Send SET_POSITION_TARGET_LOCAL_NED command to request the vehicle fly to a specified
    location in the North, East, Down frame.
    """
    msg = vehicle.message_factory.set_position_target_local_ned_encode(
        0,       # time_boot_ms (not used)
        0, 0,    # target system, target component
        mavutil.mavlink.MAV_FRAME_LOCAL_NED, # frame
        0b0000111111111000, # type_mask (only positions enabled)
        north, east, down,
        0, 0, 0, # x, y, z velocity in m/s  (not used)
        0, 0, 0, # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
        0, 0)    # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)
    # send command to vehicle
    vehicle.send_mavlink(msg)

**Comment by kripper** [comment]
> Software performance issue. You need gStreamer with GPU support, and very efficient code.

Sounds like a hack. Did you have problems getting the video stream via the SDK?
