### ISSUE TITLE
Video out from RosettaDrone 2 does not work on older non OcuSync unites

### ISSUE THREAD

**Issue by The1only** [RosettaDrone/rosettadrone#23]
The RosettaDrone 1 ONLY works with the older video systems, used on Phantom etc. My plan was to skip all older systems. Now I see that new systems like Mavic Air and Mavic Mini still uses the the old video format. And I am getting a loot of request to add video support for these to RosettaDrone 2. This is a complicated task that involves JNI C based FFMPEG and GStreamer functions. However the customers are always right so I am on my way deep in to the inner makings of the DJI video format. I do expect higher latency on these systems as I need to decode the video stream using FFMPEG and then re-encode the video using gStreame. However I will get there...!!!  If someone actually fully understands these JNI-C classes, please feel free to jump inn.

**Comment by The1only** [comment]
The new branch Video_Work got half way support or video out on older systems.

 Video can be decoded with:  sudo gst-launch-1.0 -vvv udpsrc port=5601 ! queue ! h264parse ! decodebin ! videoconvert ! autovideosink

Or if you run this in a shell on the local PC the QGC will work:

sudo gst-launch-1.0 -vvv udpsrc port=5600 ! queue ! h264parse ! decodebin ! videoconvert ! videorate ! x264enc ! rtph264pay ! queue ! udpsink host=127.0.0.1 port=5601
           
Set QGC to UDP at port 5601.

The remaining problem is the GStreamer in Rosetta is old and not compatible, so it chrashes. I am working on it.
The line abou takes the raw h.264 and ether decode it or transcode it to rtp h.264...

Pleas try this on all systems so we can verify...

**Comment by The1only** [comment]
Ahh sorry that will not work, I have the IP address sett static for testing. Still some issues with Binding to service...

**Comment by gsenkowski** [comment]
> The new branch Video_Work got half way support or video out on older systems.
> 
> Video can be decoded with: sudo gst-launch-1.0 -vvv udpsrc port=5601 ! queue ! h264parse ! decodebin ! videoconvert ! autovideosink
> 
> Or if you run this in a shell on the local PC the QGC will work:
> 
> sudo gst-launch-1.0 -vvv udpsrc port=5600 ! queue ! h264parse ! decodebin ! videoconvert ! videorate ! x264enc ! rtph264pay ! queue ! udpsink host=127.0.0.1 port=5601
> 
> Set QGC to UDP at port 5601.
> 
> The remaining problem is the GStreamer in Rosetta is old and not compatible, so it chrashes. I am working on it.
> The line abou takes the raw h.264 and ether decode it or transcode it to rtp h.264...
> 
> Pleas try this on all systems so we can verify...

Tested this with Mavic Mini, works for me.

**Comment by The1only** [comment]
I belive it shuld fully work now, if you can test with QGC.

Best regard
Terje Nilsen
9Tek AS
Norway
