### ISSUE TITLE
Some examples using DroneKit and Python to fly the DJI drones...

### ISSUE THREAD

**Issue by The1only** [RosettaDrone/rosettadrone#36]
##Two somewhat complex example that works is this:

At the moment I do not use TimeLining for absolute motion, so the drone will fly somewhat strange, as the PID in RosettaDrone2 is not tuned, this will be fixed, but there are some yaw issues I need, that complicate things.
HOWEVER, all the motion functionality is supposed to work.

The goal is that everything you can do with QGC or DroneKit and a Mavlink based drone, you should be able to do with any DJI-Mobile SDK supported drone.
All the Mavproxy and other Mavlink tools work. 

ALWAYS test with Ardupilot SITL first, then with RosettaDrone2...

## Send a velocity command with +x being NOTRH of the drone.
def send_global_ned_velocity(self, vx, vy, vz, yaw):
    msg = self.vehicle.message_factory.set_position_target_global_int_encode(
        0,  # time_boot_ms (not used)
        0, 0,  # target system, target component
        mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT,  # frame
        0b0000011111000111,  # type_mask (only speeds enabled)
        0, 0, 0,  # x, y, z positions (not used)
        vx, vy, vz,  # N, E, D velocity in m/s
        0, 0, 0,  # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
        0,float(yaw))  # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)
    self.vehicle.send_mavlink(msg)

      
    # Send a velocity command with +x being the heading of the drone.
    # For the RosettaDrone/DJI we can use yaw_rate... but then we breake Adupilot/PX4 compatibility...   
    def send_local_velocity(self, vx, vy, vz,yaw):
        msg = self.vehicle.message_factory.set_position_target_local_ned_encode(
            0,
            0, 0,
            mavutil.mavlink.MAV_FRAME_BODY_OFFSET_NED,
            0b0000011111000111, # Following ( 1 is mask OUT): yaw vel, yaw pos, force not accell, az,ay,ax, vz,vy,vx, pz,py,px 
            0, 0, 0,
            vx, vy, vz, # speed forward, right, down...
            0, 0, 0,
            0,float(yaw))  # yaw rate in radians/s...  
        self.vehicle.send_mavlink(msg)
        self.vehicle.flush()

**Comment by The1only** [comment]
PS: If you use the GOTO function in QGC you MUST move more than 50cm or it will ignore the command (a DJI thing).

**Comment by danammeansbear** [comment]
This might sound trivial but could you make a basic tutorial for this ? once you have rosetta drone working and are able to do a QGC mission, where would i start to use this? my goal is to add a python VoiceBot to automatically handle take off, landing, and assignment of missions.

**Comment by The1only** [comment]
I will, I am working on mission plans from QGC now, the goal is to have this working before Christmas.

**Comment by lukelu520** [comment]
Thanks @The1only ,it's a very useful tutorial on controlling drone using python.
Could you add an even simpler case: change arming status and takeoff the drone ?
We are trying to take off the drone using command line (with mavlink & mavros) but keep getting error, so are considering use python to solve the problem.

Best,
-- Luke

**Comment by The1only** [comment]
All the information about using the Python DroneKit to control RosettaDrone2 is here:

**https://dronekit-python.readthedocs.io/en/latest/**

And this very nice class that explains everything in detail:

**https://www.udemy.com/course/drone-programming-primer-for-software-development/**

It will eventually be 100% Mavlink compatible, so wether you fly DJI or a Mavlink drone it should be the same.
There are some limitations at the moment, but work in progress.

**Comment by The1only** [comment]
Ahhhh I know you're problem, you MUST unlock the system ( for safety) hitt the small lock button up on the right side, when it is white, THEN you can take off....  Just to prevent accidental takeoffs.

And PS: It is always smart to enter the simulation mode, and tese that everything works before actually flying. Just hit the sim button and take off... :-)

**Comment by adpmdrones** [comment]
Hi All,

following a very simple python script that connects to RosettaDrone and print out some vehicle parameters:

Usage:
 **python rosetta_drone.py --connect=udp:your_gcs_ip_address:14550**

your_gcs_ip_address is the address of the computer where the script is running 

I'll post also a more complex script with some commands like takeoff , starting a mission and so on

Ciao 

/Luca

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from dronekit import connect, VehicleMode
import time
import argparse
import datetime

#Set up option parsing to get connection string                                                                                                                                                                   $parser = argparse.ArgumentParser(description='Print out vehicle state information. Connects to SITL on local PC by default.')
parser.add_argument('--connect',
                   help="vehicle connection target string. If not specified, exit.")
args = parser.parse_args()

connection_string = args.connect
connection_drone_id = args.uavid
sitl = None

#Start SITL if no connection string specified
if not connection_string or not connection_drone_id:
        print("Pls specify the connect parameters (--connect)")
        exit()

# Connect to the Vehicle.
#   Set `wait_ready=True` to ensure default attributes are populated before `connect()` returns.
print("\nConnecting to vehicle on: %s" % connection_string)
vehicle = connect(connection_string, wait_ready=True)

cmds = vehicle.commands
cmds.download()
cmds.wait_ready()

vehicle.wait_ready('autopilot_version')

##########
# Start
##########
while True:
        print vehicle.battery.level
        print vehicle.system_status.state
        print vehicle.armed
        print vehicle.heading
        print vehicle.groundspeed
        print vehicle.gps_0.fix_type
        print vehicle.gps_0.satellites_visible
        print vehicle.location.global_frame.lat
        print vehicle.location.global_frame.lon
        print vehicle.location.global_frame.alt
        print vehicle.heading
        print vehicle.groundspeed
        print vehicle.velocity[2]
        print vehicle.home_location.lat
        print vehicle.home_location.lon
        print vehicle.home_location.alt
        print vehicle.commands.next
        print vehicle.commands.count
```

**Comment by The1only** [comment]
Perfekt, I work round the clock to get the mission planning working. The conversion from Mavlink to DJI and back is almost ready.

**Comment by danammeansbear** [comment]
This is awesome 👌

**Comment by adpmdrones** [comment]
> Perfekt, I work round the clock to get the mission planning working. The conversion from Mavlink to DJI and back is almost ready.

Awesome!!!

**Comment by lukelu520** [comment]
We are stuck in change mode from Stabilize to GUIDED. (by using the command `vehicle.mode = VehicleMode("GUIDED")`)
We've unlocked the safety by clicking the top-right icon, making it white.

To our knowledge, drone can not be armable without going to GUIDED mode. 
Is there anyway to set the mode to GUIDED, maybe inside rosettadrone ?

Hope to hear your expertise.

Best,
-- Luke

ps: we are testing DJI mini.

**Comment by The1only** [comment]
If I remember right the DJI drone switches automatically on a takeoff command from mavlink, ignore the error and continue to takeoff. But RosettaDrone expect 'P' mode on the controller (Mavic 2 Pro), and you must click on the "lock" so it becomes white NOT geeen before issuing the command.

**Comment by lukelu520** [comment]
Thanks for your persistently kind help, @The1only . By ignore mode change and arm check, we are able to takeoff ! 
To help more newbie folks, we paste the simple takeoff script below:

===
```
# hello world example: Takeoff your drone to a targetAltitude. 
# Advice: better to remove drone propellers before executing the script

from dronekit import connect
import time

vehicle = connect('udpin:hostip:port', wait_ready=True)
vehicle.wait_ready('autopilot_version')
targetAltitude = 1.5  # in meter
vehicle.simple_takeoff(targetAltitude)

while True:
    print(" Altitude: ", vehicle.location.global_relative_frame.alt)
    if vehicle.location.global_relative_frame.alt>=targetAltitude*0.95:
        print "Reached target altitude"
        break
    time.sleep(1)
```


We are working on virtual joytick and a simple control feature based on your example. 

Best,
-- Luke

**Comment by The1only** [comment]
PS: remember that if you hit the SIM button on startup you can take off and fly like this without actually taking off. The SIM button enables the built inn DJI HITL module.  The drone must be rebooted after using the Simulation mode.

**Comment by lukelu520** [comment]
Nice to know the feature !
BTW, was wondering if you know how to construct a mavlink msg for LANDING ? So far we know it may require:

> mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT, mavutil.mavlink.MAV_CMD_NAV_LAND

inside the mavlink packet.

If you know any help manual on mavlink msg construction, please kindly let us know.

Thanks,
-- Luke

**Comment by The1only** [comment]
def return_home_and_land(self):
        # Send Drone home and land...        
        print("Waiting for drone to enter RTL flight mode")
        self.vehicle.mode = VehicleMode("RTL")
        time.sleep(5)
        while not self.vehicle.mode.name == 'RTL':
            time.sleep(0.5)

        print("Waiting for drone to return to landing")
        while self.vehicle.armed is True:
            print("Current Altitude: %f" % self.vehicle.location.global_relative_frame.alt)
            time.sleep(1.0)
        
        print("Landed...")

    def land(self):
        print("Now let's land")
        self.vehicle.mode = VehicleMode("LAND")
        time.sleep(5)

        print("Waiting for landing")
        while self.vehicle.mode == 'LAND' and self.vehicle.armed is True:
            print("Current Altitude: %f" % self.vehicle.location.global_relative_frame.alt)
            time.sleep(1)

        print("Landed...")

**Comment by The1only** [comment]
In QGC you can also point and click on the location you want the drone to "goto" and it will.

**Comment by lukelu520** [comment]
The problem we met is VehicleMode doesn't take effect. We've tested multiple VehicleMode such as GUIDED, LAND, but none of them is successfully set.

Alternatively, vehicle.send_mavlink(msg) works. Since Rosetta Drone has MAV_CMD dictionary, so maybe we could send command to corresponding mission, s.t. MAV_CMD_NAV_LAND = 21;

Hope to hear your expertise.

Best,
-- Luke

**Comment by The1only** [comment]
Hmm strange I have been using this code for over one year now without issues. Let me look into it.

No works fine, both RTL and LAND commands are OK. 

If you are used to PX4 or Ardupilot, do not get too hooked up in how the mode changes work, DJI does this totally different. The DJI drone itself controls mode changes, so the RosettaDrone convert mode changes to commands, like land or return to  launsh. You can not directly SET a mode change. 

Also DJI handles RTL strange if you do not fly more than 10 meters or so from takeoff, then they simply land I've noticed,

**Comment by lukelu520** [comment]
Thanks for your prompt reply. 
In the meantime, we will also log the behavior inside doInBackground of MainActivity.java.
Hope to print out msg_cmd.command for the analysis.

**Comment by The1only** [comment]
It's allready there, just select the LOGCAT windows and enter MAV in the text window and select Verbose...
You will the see all you're commands.

**Comment by lukelu520** [comment]
We found that MAV_CMD_DO_SET_MODE cause the issue, so we logcat it:

`sysid:255 compid:0 param1:1.0 param2:9.0 param3:0.0 param4:0.0 param5:0.0 param6:0.0 param7:0.0 command:176 target_system:1 target_component:0 confirmation:0`

Then Rosetta Drone executes `changeFlightMode((int) msg_cmd.param1);` 

That's weird, param1 is 1.0 (it's the altitude); But param2 is 9, which seems matches LAND code better.
Once we modify the line to `changeFlightMode((int) msg_cmd.param2);`,  Landing works!

Hope to hear your expertise on the parameter discrepancy. Does it cause by different mavlink protocol used in different DJI model ?

-- Luke

**Comment by The1only** [comment]
Can you provide a short test case that recreates this problem?
As you know there are two different MAVlink commands for changing the mode, both end up doing the same. 
Maybe there is something there. The long command 176 uses parameter 1, the command 11 uses parameter 2. However, in RosettaDrone we use parameter 3 (Custom Mode). This goes all the way back but might need to change. 

**https://mavlink.io/en/messages/common.html**

The only modes that will have any effect are these:
AUTO
BRAKE
RTL
LAND

And at the moment the only ones that are confirmed to work is:
RTL
LAND

As we still work on the waypoint functionality.
All other modes the Drone handles by itself, nothing we can do. So for compatibility, you would still put them in you're script,  but ignore the response for RosettaDrone. This way you can fly complex missions on both DJI and a MAVlink drone without changing the code. Works fine for me.

**Comment by lukelu520** [comment]
The python code of dronekit is below. VehicleMode("LAND") send command 176 to RosettaDrone, and  RosettaDrone uses command 176 to do the case MAV_CMD_DO_SET_MODE, and then changeFlightMode((int) msg_cmd.param2) needs to use to set proper mode for RosettaDrone.

The long command is: `sysid:255 compid:0 param1:1.0 param2:9.0 param3:0.0 param4:0.0 param5:0.0 param6:0.0 param7:0.0 command:176 target_system:1 target_component:0 confirmation:0`

Not sure why LAND parameter (9.0) is not put in param 1. It's put in 2 for Custom Mode. 

```
    def land(self):
        print("Now let's land")
        self.vehicle.mode = VehicleMode("LAND") 
        time.sleep(5)

        print("Waiting for landing")
        while self.vehicle.mode == 'LAND' and self.vehicle.armed is True:
            print("Current Altitude: %f" % self.vehicle.location.global_relative_frame.alt)
            time.sleep(1)

        print("Landed...")
```

**Comment by The1only** [comment]
You are on to something, thank you.

On my MAC with all the latest modules, I get the same issue as you, that is, the Mode change command uses parameter 2, as it should. When I change the code to use parameter 2 rather than 1 then all the mode changes work again and I can take off and land.
However on my main Linux system that pulled modules 6 months ago. I need to use parameter 1.
I will check the DroneKit issue list, they may have fixed this.

Greate catch...

**Comment by The1only** [comment]
I used a setup from a Udemy class years ago...  
I will check-in the fix and update all my systems.

**Comment by The1only** [comment]
If you check out the “Work” branch it is fixed. 
I now uses Parameter 2 and can confirm it works on my MAC with all the latest.
But now it’s a problem on older systems.

**Comment by lukelu520** [comment]
Thanks for your fix, @The1only ! 

We are working on velocity control, regards to your example "**Send a velocity command with +x being the heading of the drone.**" on the top of the discussion thread:

What is `int(x10000000), int(y10000000), float(z)` ?  Our python can not recognize x10000000 and y10000000.

And the line: `speed, speed, 1.0, # x, y, z velocity in m/s`, why you give 1.0 m/s for the z direction ?

Best,
-- Luke

**Comment by adpmdrones** [comment]
We're experiencing the same issues:

from python script, we're able to takeoff and go to specified lat,lon

We've also an issue with goto command, the altitude will change to 1.2m

We're unable to issue command like RTL or LAND too

**Comment by The1only** [comment]
Hmm We just fixed RTL did we not???
I installed everything fresh yesterday evening and it was working just fine.
It seems some DroneKit versions uses parameter 1 and some uses the correct parameter 2
Make sure you are on the "Work" branch

Sorry for the bad example, I updated it now.

**Comment by adpmdrones** [comment]
I must recompile Rosetta Drone from the work branch?

**Comment by The1only** [comment]
To get the latest fixes YES, we will not update master until Waypoint flying is working.

**Comment by The1only** [comment]
OR you can just patch this:

                    case MAV_CMD_DO_SET_MODE:
                        changeFlightMode((int) msg_cmd.param2);
                        break;

**Comment by The1only** [comment]
Ahh the GOTO command Altitude was also fixed some time back.
Maybe you should just upgrade to the "Work" patch.
Then you will also get DJI SDK 4.14 ( the brand new open)

**Comment by adpmdrones** [comment]
Compiled with the work branch and SDK 4.14

Now RTH and LAND commands are ok
TAKEOFF it's OK
but the previous GOTO command (from python) does not work anymore

Still testing

BTW I cannot use GOTO from QGCS

**Comment by The1only** [comment]
OK thank you I will fix.
Can you send the Python code you use for the GOTO?

**Comment by adpmdrones** [comment]
<pre>
# Arm and takeoff
arm_and_takeoff(7) <-- OK

time.sleep(5)

print("Going towards first point for 30 seconds ...")
vehicle.mode = VehicleMode("GUIDED")
point1 = LocationGlobalRelative(41.932030,  12.631848, 5)
point2 = LocationGlobalRelative(41.932327,  12.631982, 5)
vehicle.simple_goto(point1)
time.sleep(20)
vehicle.simple_goto(point2)
time.sleep(20)
print("Returning to Launch")
vehicle.mode = VehicleMode("RTL") <-- OK

</code></pre>

**Comment by The1only** [comment]
Perfect, never tested that command. Give me an hour...

**Comment by adpmdrones** [comment]
Take your time, thank you

With the master branch, the GOTO command worked with the altitude issue

**Comment by adpmdrones** [comment]
Let me know which command you use for guided

**Comment by The1only** [comment]
OK This is part of a DJI issue that any mission MUST have two or more waypoints.
To fix this we use a trap, but somehow this fails now. I'll fix it.

I use another GOTO built from MAVlink Long command, but this is better so just way until I can test and verify my fix.

**Comment by The1only** [comment]
I do not have a system to test on, but I belive I fixed the GOTO, and also added support for the old MissionItem/goto command that some still use...

**Comment by adpmdrones** [comment]
Tested the updated work branch:

1 - simple_goto() dronekit function works as expected (altitude/heading ok)
2 - loading WPs (mission) from QGCS works as expected (1)
3 - GOTO from QGCS works as expected (2)


Note:
1) After loading all the WPs, QGCS returns an error regarding the last ACK not correctly received but the mission was uploaded correctly
2) after sending from QGCS the GOTO command returns an error but the command it's executed normally

**Comment by adpmdrones** [comment]
I'll post some screenshots and python code later

**Comment by adpmdrones** [comment]
![image](https://user-images.githubusercontent.com/4736951/102913475-16dc3e00-447f-11eb-9329-ea5c70b3774f.png)

that's the error after uploading waypoint (the mission works correctly)

**Comment by The1only** [comment]
That is a known error I will fix it after I get the waypoint download to work (read back from the drone).On Dec 22, 2020 17:57, ADPM Drones <notifications@github.com> wrote:

that's the error after uploading waypoint (the mission works correctly)

**Comment by adpmdrones** [comment]
> That is a known error I will fix it after I get the waypoint download to work (read back from the drone).On Dec 22, 2020 17:57, ADPM Drones <notifications@github.com> wrote: that's the error after uploading waypoint (the mission works correctly) —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks!!!

The same happens when using GOTO from QGCS

![image](https://user-images.githubusercontent.com/4736951/102919351-f9ac6d00-4488-11eb-9652-262625d104dc.png)

**Comment by adpmdrones** [comment]
After some testing, we have reached a very reliable interaction between DJI and Mavlink (dronekit) scripts.

TakeOff, Landing, Brake, RTH, GOTO everything works fine from dronekit/python.
We need to test the mission loading and execution via dronekit/python.
We have also developed a REST API interface for getting the telemetry and send the commands to Rosetta Drone

More on this later

**Comment by The1only** [comment]
Look forward to a rest api  example or two.Marry Christmas.

**Comment by danammeansbear** [comment]
Can't wait for this!

**Comment by adpmdrones** [comment]
Following an example of reading UAV data and publish them in a JSON format via HTTP:


<pre>#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
© Copyright 2019-2020, ADPM Drones.

Get  status from REST API (https://XXXXXXXXXXX)
vehicle status in JSON format returned:
{
  "status": {
    "status": "ACTIVE",
    "lastReachedWaypointId": 3,
    "name": "Drone ACME",
    "uavId": "1",
    "timestamp": "2020-12-13T07:18:34.867608+00:00",
    "EKF_status": true,
    "groundSpeedMetersPerSecond": 4.983015060424805,
    "is_armable": true,
    "heading": 274,
    "batteryRemainingPercent": 0,
    "lat": 99.729751,
    "alt": 591.88,
    "verticalSpeedMetersPerSecond": 0,
    "satellites": 10,
    "lng": 88.3460402,
    "armed": true,
    "fixType": 6,
    "channel": "LTE",
    "FlightMode": "AUTO"
  },
  "command": "HEARTBEAT"
}
"""
from __future__ import print_function
from dronekit import connect, VehicleMode
import time
import requests
import json
import datetime
import os
import pytz

"""
Set up option parsing to get connection string
"""
import argparse
parser = argparse.ArgumentParser(description="Read out vehicle state information and publich in JSON format.")
parser.add_argument("--connect",
                   help="vehicle connection target string.")
args = parser.parse_args()

connection_string = args.connect

"""
Connect to the Vehicle.
   Set `wait_ready=True` to ensure default attributes are populated before `connect()` returns.
"""
print("\nConnecting to vehicle on: %s" % connection_string)

while True:
	try:
		vehicle = connect(connection_string, wait_ready=True)
	except:
		print ("Some Dronekit error")
		"""
		Retry connection
		"""
		continue
	# if everything ok proceed
	break

vehicle.wait_ready("autopilot_version")

"""
Get all vehicle attributes (state)
"""
print("\nGet all vehicle attribute values:")
print(" Global Location: %s" % vehicle.location.global_frame)
print(" Global Location (relative altitude): %s" % vehicle.location.global_relative_frame)
print(" Local Location: %s" % vehicle.location.local_frame)
print(" Attitude: %s" % vehicle.attitude)
print(" Velocity: %s" % vehicle.velocity)
print(" GPS: %s" % vehicle.gps_0)
print(" Battery: %s" % vehicle.battery)
print(" EKF OK?: %s" % vehicle.ekf_ok)
print(" Last Heartbeat: %s" % vehicle.last_heartbeat)
print(" Heading: %s" % vehicle.heading)
print(" Is Armable?: %s" % vehicle.is_armable)
print(" System status: %s" % vehicle.system_status.state)
print(" Groundspeed: %s" % vehicle.groundspeed)    # settable
print(" Airspeed: %s" % vehicle.airspeed)    # settable
print(" Mode: %s" % vehicle.mode.name)    # settable
print(" Armed: %s" % vehicle.armed)    # settable

drone_id = 1
channel = "LTE"
path = "/home/yyyyyyyyy/"

print("Vehicle tracking info process running...")

try:
	while True:
		d = datetime.datetime.now(tz=pytz.utc).isoformat()
		my_json = {
					"command": "HEARTBEAT",
					"status":
					{
						"name": "Drone ACME",
						"uavId": str(drone_id),
						"timestamp" : d,
						"channel" : channel,
						"status": vehicle.system_status.state,
						"is_armable": vehicle.is_armable,
						"armed": vehicle.armed,
						"batteryRemainingPercent": vehicle.battery.level,
						"fixType": vehicle.gps_0.fix_type,
						"satellites": vehicle.gps_0.satellites_visible,
						"lat": vehicle.location.global_frame.lat,
						"lng": vehicle.location.global_frame.lon,
						"alt": vehicle.location.global_frame.alt,
						"heading": vehicle.heading,
						"groundSpeedMetersPerSecond": vehicle.groundspeed,
						"verticalSpeedMetersPerSecond" : vehicle.velocity[2],
						"lastReachedWaypointId": vehicle.commands.next,
						"FlightMode": vehicle.mode.name,
						"EKF_status": vehicle.ekf_ok
					}
				}

		with open(path + "pos.json", "w") as json_file:
			json.dump(my_json, json_file, indent = 4)
		os.system("sudo mv " + path + "pos.json /var/www/html/xxxxxxxxx/index.html")
		#json_file.close()
		time.sleep(0.1)
except:
	print("An exception occurred")
	pass
"""
dummy data on exit
so it"s possible to check for no data coming from vehicle
"""
d = datetime.datetime.now(tz=pytz.utc).isoformat()
my_json = {
			"command": "HEARTBEAT",
			"status":
			{
				"name": "Drone ACME",
				"uavId": str(drone_id),
				"timestamp" : d,
				"channel" : channel,
				"status": None,
				"is_armable": None,
				"armed": None,
				"batteryRemainingPercent": None,
				"fixType": None,
				"satellites": None,
				"lat": None,
				"lng": None,
				"alt": None,
				"heading": None,
				"groundSpeedMetersPerSecond": None,
				"verticalSpeedMetersPerSecond" : None,
				"lastReachedWaypointId": None,
				"FlightMode": None,
				"EKF_status": None
			}
		}

with open(path + "pos.json", "w") as json_file:
	json.dump(my_json, json_file, indent = 4)
os.system("sudo mv " + path + "pos.json /var/www/html/xxxxxxxxxx/index.html")
json_file.close()

"""
Close vehicle object before exiting script
"""
print("\nClose vehicle object")
vehicle.close()

print("Completed")
</code></pre>

**Comment by adpmdrones** [comment]
For public webhook endpoints, I use http://www.webhook.site

Very powerful!!!!

**Comment by The1only** [comment]
https://github.com/patrickelectric/mavlink2rest

**Comment by adpmdrones** [comment]
> https://github.com/patrickelectric/mavlink2rest

Good catch!!!

Thanks!!!

**Comment by adpmdrones** [comment]
Tested right now with Rosetta Drone (mav2rest)

![image](https://user-images.githubusercontent.com/4736951/103088574-840ce200-45eb-11eb-9186-6bb72a134352.png)

**Comment by The1only** [comment]
If it works, give the guy a feedback, and we get more attention also to our project.

**Comment by adpmdrones** [comment]
> If it works, give the guy a feedback, and we get more attention also to our project.

Already done!

**Comment by The1only** [comment]
In this tread they mention POST also, did you test that?

https://discuss.ardupilot.org/t/mavlink-to-rest-api/51660

**Comment by The1only** [comment]
Ps: I have also tested the Mavproxy, it also works. Moust interesting is the abillity to split Mavlink streams, and the command line GCS.

**Comment by adpmdrones** [comment]
> Ps: I have also tested the Mavproxy, it also works. Moust interesting is the abillity to split Mavlink streams, and the command line GCS.

I used mavproxy too for splitting mavlink stream to qgcs and my REST API scripts

**Comment by adpmdrones** [comment]
> In this tread they mention POST also, did you test that?
> 
> https://discuss.ardupilot.org/t/mavlink-to-rest-api/51660

I've tested sending RTH change mode (the same I use in my python script) but Rosetta Drone does not respond

<pre>{
  "header": {
    "system_id": 1,
    "component_id": 1,
    "sequence": 0
  },
  "message": {
    "type":"COMMAND_LONG",
    "param1":1.0,
    "param2":6.0,"param3":0.0,"param4":0.0,"param5":0.0,"param6":0.0,"param7":0.0,
    "command":{
      "type":"MAV_CMD_DO_SET_MODE"
    },
    "target_system":0,
    "target_component":0,
    "confirmation":0
  }
 }
</code></pre>

**Comment by danammeansbear** [comment]
Does anyone have an idea how to map out a polygon mission based around a center point EX. creating a rectangle mission pattern based on current or assigned position
I have this script i use to get the distance of one point to another 
'
R = 6373.0
radius of the Earth


lat1 = math.radians(52.2296756)
coordinates

lon1 = math.radians(21.0122287)
lat2 = math.radians(52.406374)
lon2 = math.radians(16.9251681)

dlon = lon2 - lon1
change in coordinates

dlat = lat2 - lat1

a = math.sin(dlat / 2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2)**2
Haversine formula

c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
distance = R * c

print(distance)
OUTPUT
278.54558935106695
'

and this algorithm with the help of my teacher to get the cordinates of an unknown point give then distance.
The formula is
x2=x1+d×cosθ,y2=y1+d×sinθ,
d = the distance from (x1,x2) to (y1,y2).

How would i algorithmically compute a polygon and assign cordinates to the points of it? sorta like how mission planner does this but command line format

**Comment by The1only** [comment]
Nice project, There are several manuals for dronekit online. You will find everything there, combined with this page.

I will make a manual/wikki at some time, but now I got no time.

**Comment by The1only** [comment]
Try the Work branch, it got some nice fixes.
If you got problems I’ll jump right at it.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by The1only** [comment]
Just use takeoff goto(lat lon) rtl() 
It’s all described in the DeonKit for python manual by 3DR.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by lukelu520** [comment]
Dear Dronekit friends,

We are trying to use DroneKit's Gimbal function to change the pitch of gimbal, but not very sure if it is compatible with rosettadrone.

I was wondering if someone tried DroneKit to control camera gimbal. Hope to know what kind of DJI model works.

-- Luke

**Comment by The1only** [comment]
No, you have to use Dronekit servo functions. As described in the readme cannel 8 and 9 if I remember right. However send me a Dronekit code example and I will make it work.

**Comment by lukelu520** [comment]
Great tips @The1only ! We do find below important lines in MAVLinkReceiver which can map to DroneKit Servo control

```
case MAV_CMD_DO_SET_SERVO:
    mModel.do_set_Gimbal(msg_cmd.param1, msg_cmd.param2);
    break;
```
As we know, do_set_Gimbal is implemented in DroneModel, showing that channel 9 is for pitch control. (8 is for yaw)

We are working on Mavic. So just curious about why you said in #14 Mavic might have issue on controlling gimbal, is it fundamentally restricted by DJI SDK ?

**Comment by lukelu520** [comment]
Update @The1only : Good news, we are able to make camera looking down (i.e. bird's view) by changing the servo position between 1500 and 1000. 

However, we got issue on making the camera looking up. We changed the servo position up to 2000 but there is no response.

We are testing DJI mavic mini, codes are below:

> msg = self.vehicle.message_factory.command_long_encode(
            0, 0,  # target_system, target_component
            mavutil.mavlink.MAV_CMD_DO_SET_SERVO,  # command
            0,  # confirmation
            9,  # servo number
            position,  # servo position between 1000 and 2000
            0, 0, 0, 0, 0)  # param 3 ~ 7 not used


-- Luke

**Comment by The1only** [comment]
Tilt works fine, but you can not do 2000 that would be stright up, try 1600 and increase.

Pan is the real issue, only work on ground, not in air.

**Comment by lukelu520** [comment]
Thanks for your reply so that we are able to realize a 5.5 value corresponds to 1 degree tilt.

**Comment by patrickelectric** [comment]
Hi, I'm the creator of mavlink2rest, I'm a bit lost, is there any integration for it in this project, is there any work in progress for that or is this an acceptable contribution ?

**Comment by The1only** [comment]
I am the creator of Rosettadrone2. 
As we do a mavlink2DJI as part of our project, and you do mavlink2rest, som has then done rest to DJI, using both projects. And the reported it working.

You do great work, let’s work more together.

**Comment by avncalst** [comment]
Just had a successful test flight with my mavic mini controlled by a artificial intelligence python script to avoid obstacles. First results are promising. Congratulations to  "The1only" for this excellent Rossetadrone2 work.

**Comment by fajrulfx** [comment]
Dear Dronekit friends,

I've successfully connect Rosetta Drone and Dronekit, and use python script to interact with my Drone (Mavic Mini). It works with `simple_takeoff` command, but the altitude of my drone is stuck at 1 m although I set a higher altitude. Other command like `simple_goto` also not working, my drone doesn't move anywhere.

Any idea how to solve this issue? Thanks.

**Comment by Newguyonthefield** [comment]
> This might sound trivial but could you make a basic tutorial for this ? once you have rosetta drone working and are able to do a QGC mission, where would i start to use this? my goal is to add a python VoiceBot to automatically handle take off, landing, and assignment of missions.

Did you find the way? i wanna do something like that with a Mavic Mini

**Comment by Newguyonthefield** [comment]
> 

I would love to have a little guide for that. I’m trying to connect my Mavic Mini

**Comment by The1only** [comment]
Read the DroneKit for Python manuals, it’s all there.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by kripper** [comment]
> Just had a successful test flight with my mavic mini controlled by a artificial intelligence python script to avoid obstacles. First results are promising. Congratulations to "The1only" for this excellent Rossetadrone2 work.

Hi @avncalst, I saw your video on YouTube.
Which repo are you using? I saw some reports of problems dealing with the video stream. Have they been fixed?

I'm interested in writing AI scripts for the mini SE.

**Comment by The1only** [comment]
Thank you Cristopher,It feels god when someone fully understands ones work. It was presisly this I designed Rosettadrone 2 for. I did AI powerline inspections fully autonomous without any human interaction or pre planning.Best regardTerje Nilsen9Tek ASNorwayOn 9 Jan 2023, at 03:00, Christopher Pereira ***@***.***> wrote:﻿

Just had a successful test flight with my mavic mini controlled by a artificial intelligence python script to avoid obstacles. First results are promising. Congratulations to "The1only" for this excellent Rossetadrone2 work.

Hi @avncalst, I saw your video on YouTube.
Which repo are you using? I saw some reports of problems dealing with the video stream. Have they been fixed?
I'm interested in writing AI scripts for the mini SE.

**Comment by avncalst** [comment]
Hi @kripper  my code can be found on GitHub https://github.com/avncalst/drone_cnn/tree/master/rosetta. I had no problems video streaming using gstreamer.

**Comment by kripper** [comment]
> Hi @kripper my code can be found on GitHub https://github.com/avncalst/drone_cnn/tree/master/rosetta. I had no problems video streaming using gstreamer.

Thanks. I will replicate your environment.
Are you using The1only's repo?

I'm asking because there is a fork with additional enhancements for Mini 2 here:
https://github.com/m4xw/rosettadrone_mini2

**Comment by avncalst** [comment]
I compiled with Android Studio "The 1 only's" repo june 2021. So the enhancements for the Mini 2  were not yet available

**Comment by paw-krz** [comment]
Do you know if it's possible to control attitude (roll, pitch, yaw)? I tried code from dronekit examples (https://github.com/dronekit/dronekit-python/blob/master/examples/set_attitude_target/set_attitude_target.py), but it does't work, nothing changes

**Comment by kripper** [comment]
Closing. Discussion continues here: https://github.com/RosettaDrone/rosettadrone/discussions/133

**Comment by kripper** [comment]
> I compiled with Android Studio "The 1 only's" repo june 2021. So the enhancements for the Mini 2 were not yet available

Hi @avncalst, you were probably using a `MINI` (not `MINI SE`). Good to know that video streaming works with the MINI.
Could you please test video streaming using latests version of RosettaDrone?
