### ISSUE TITLE
mavlink & socket details for bidirectional communication

### ISSUE THREAD

**Issue by robbiedood** [RosettaDrone/rosettadrone#41]
Dear rosettadrone friends,

The git is really nice, we've studies some core parts of these codes and use them very well from GCS side.

Our external GCS is able to get telemetry from the rosettadrone device (i.e. Android device installed rosettadrone). Now we are figuring out how to send telemetry to rosettadrone device in order to achieve bidirectional communication.

In MainActivity, there are core "createTelemetrySocket" & "GCSCommunicatorAsyncTask", the default port is 14550 as the external GCS's receiving port. But we were still little bit confused by the bidirectional communication workflow, were wondering what is the port and address setting (or what's the default value) to allow rosettadrone device to receive telemetry from GCS ? (is the core module "MAVLinkReceiver" ?)

Hope to hear your expertise and get some guides.

Best,
-- Luke

**Comment by The1only** [comment]
You simply sends data back on the same socket you receive data, no need for an additional socket. RosettaDrone supports two independent connections, however if you can use one for receiving and one for sending I have never tested.

Terje

**Comment by The1only** [comment]
If you click on the config button up in the right corner, you can set the ip destination, and port, and the secondary port etc. 
All this is well tested.

**Comment by lukelu520** [comment]
@The1only , thanks for your support !  It's nice to learn the same socket would be used and no need for an additional socket.

Just a follow-up question: what's the fcu protocol version Rosetta Drone is using, is it v2.0 or others ?

---

Will follow basic [hello drone tutorial](https://dronekit-python.readthedocs.io/en/latest/guide/quick_start.html#basic-hello-drone) to send a test msg to Rosetta Drone.

-- Luke

**Comment by The1only** [comment]
Also look in the examples thread, there is an example in the end there.

**Comment by lukelu520** [comment]
Rosetta Drone uses ArduPilot, I assume it's APM rather than PX4 stack.
But it's based on APM 1 or APM 2?  There are warning on "your FCU don't support AUTOPILOT_VERSION, switched to default capabilities"

**Comment by The1only** [comment]
No there is not PX4 nor APM code in RosettaDrone, it's DJI flight controller. It uses the Mavlink 2 stack thats all, and the DJI sdk stack, but there is now flightcontroller in RosettaDrone...

**Comment by MariusBeul** [comment]
@The1only
Sorry to reopen this issue. You state that Rosettadrone uses MAVLINK 2, but when I understand correctly, the [Parser.java](https://github.com/The1only/rosettadrone/blob/master/app/src/main/java/com/MAVLink/Parser.java) file [deserializes ](https://mavlink.io/en/guide/serialization.html) only MAVLINK 1 packages correctly. Also the Packet start marker is set to [0xFE](https://github.com/The1only/rosettadrone/blob/5bdcdce184a964e5fd5c9e6d75bc3f28b910bdda/app/src/main/java/com/MAVLink/MAVLinkPacket.java#L103) (254) which indicates MAVLINK 1.
