### ISSUE TITLE
Support for lightbridge based vehicles

### ISSUE THREAD

**Issue by boschet** [RosettaDrone/rosettadrone#49]
Hey, 

this is a more general question. All the drones tested with use OccuSync in various versions. I'm using a M600Pro, which uses a lightbridge 2 connection. Are there fundamental roadblocks for the use with such a system?

**Comment by The1only** [comment]
DJI have done small changes on alll there systems. So every system must be tested and adapted. We got Inspire 1, Matrice 100 and Phantom 3 to work, they all uses the old system. The 600 I have never tried, nor the Lightbridge video link. Ether you will have to work out the problem, find someone that will, or find a way to send a system to me.
