### ISSUE TITLE
Error clicking the Open button in the App

### ISSUE THREAD

**Issue by DIOGOFIGUEIRA** [RosettaDrone/rosettadrone#57]
The app has opened and the status is: DJIAircraft connected.
The Open button turns blue.
Below appears: Phantom 4 Pro, DJI SDK Version: 4.14.
However, when I click the Open button, the screen goes black and closes the app.
The QGroundControl app stays connected for a while.

I'm using the app on a motorola moto G with android 5.1.
I tried to run on an Asus Nexus 7 with Android 6.1 , but it gave an error.

What could be happening?

Thanks.

Diogo Figueira

**Comment by The1only** [comment]
With the drone DISCONNECTED try to hit the image on the login screen 6 times, the system will enter test mode. you can then hit the blue open button. If it fails to open, something went wrong in building the project, if it opens fine, there is something with eh Phantom 4, most likely a Video trick we did not anticipate (I have not tested Phantom 4)
