### ISSUE TITLE
Override guided point does not work

### ISSUE THREAD

**Issue by adpmdrones** [RosettaDrone/rosettadrone#58]
Hi,
I'm attempting to send guided point B to drone while it is still in guided but toward previously sent guided point A. Unfortunately drone continues to go toward guided point A. I attempted to set "brake" mode, and then to provide guided point B, but nothing happens (rather, in this situation drone can't move at all, neither to point A if sent again).
I tried using Mission Planner simulator instead of Rosetta/DJI and it works.
Is this a DJI SDK limitation?
Thank you in advance

**Comment by The1only** [comment]
I belive you are ahead of development, feel free to dig inn.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by TheMisterFish** [comment]
> Is this a DJI SDK limitation?

No, it is not yet programmed I believe.

**Comment by kripper** [comment]
Check latest version.
