### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by TheMisterFish** [RosettaDrone/rosettadrone#66]
**Is your feature request related to a problem? Please describe.**

Add more code documentation for contributors

**Describe the solution you'd like**
Either use the wiki or a docs folder with different markdown files containing documentation on parts of the code.

**Describe alternatives you've considered**
docs folder or wiki could be used. Preferable docs as this will be included in one repository rather than two.

Docs for the different java classes as well as contributing documentation if possible

**Comment by TheMisterFish** [comment]
Example document on FTP:
https://github.com/lilfish/Delta-FlowerPower/wiki/Droneapp-Python-FTP

Example documentation on the drone app:
https://github.com/lilfish/Delta-FlowerPower/wiki/Drone-app

(May be fully copied)

**Comment by kripper** [comment]
Thanks, we added your doc in the README page.
