### ISSUE TITLE
Dronekit connection

### ISSUE THREAD

**Issue by gab933** [RosettaDrone/rosettadrone#68]
Hi,
I have connection issue with Rosetta and Dronekit. When I launch first time Rosetta and then I connect dronekit everything works. But if I disconnect dronekit, and then I attempt to connect it again (by leaving Rosetta running), I incur in connection timeout. Therefore I have to close Rosetta and launching it again.
How can I solve this problem?
Thank you in advance

**Comment by The1only** [comment]
Do you receive status but can’t send any commands? Or do you get nothing?

Rosettadrone sends data blindly out on port 14550 (default) and knows nothing about the receiving side or even if any one is listhning.

Can’t say I have ever seen this problem, and I use Dronekit all the time.

Are you shure you exit Dronkit propperly, with closed UDP port.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by gab933** [comment]
Thank you for your reply.
I have problems with re-connecting dronekit by leaving Rosetta up. I close dronekit in the correct way by using vehicle.close() function. When I stop and re-open Rosetta, connection works as expected, so it looks like Rosetta toils to re-establish connection with dronekit. I performed a simulation with Arducopter Mission Planner (as source instead of Rosetta) and I successfully close and re-open dronekit connection lot of times without re-launching it.
Best regards,

Gabriele

**Comment by The1only** [comment]
Hmmm, I do this all the time, I will check my code, maybe there is a trick I have forgotten. 
I really do not see how this can be.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by gab933** [comment]
Hi Terje,
an update: I noticed that by setting wait_ready=False in dronekit.connect function the problem disappeared. I don't know this can help.
Thank you,

Gabriele

**Comment by gab933** [comment]
Hi,
further update: with wait_ready=false connection established in about 1 second, but unfortunately when I disconnect dronekit and reconnect it again (with Rosetta up), even if it results I'm connected with dronekit, commands are not received. This situation is the same as the one I described in first posts. I'll further investigate,
Regards,

Gabriele

**Comment by The1only** [comment]
This is how I do it, never har and Connection issues:

 def connect(self, connection_string):

        print("Connecting...")
        if not connection_string:
            from dronekit_sitl import SITL, start_default
            self.sitl = SITL()
            self.sitl.download('copter', '3.3', verbose=True)
            sitl_args = ['-I0', '--model', 'quad', '--home=60.4094,10.4911,0,0']
            self.sitl.launch(sitl_args, await_ready=True, restart=True)
            connection_string = self.sitl.connection_string()
            print("Simulate mode!!!!")

        self.vehicle = connect(connection_string, wait_ready=True)
        self.vehicle.wait_ready('autopilot_version')        
        self.just_seen = self.vehicle.location.global_relative_frame
        return self.vehicle

**Comment by gab933** [comment]
Hi,
I use exactly the same to connect. Sorry for my redundancy, I'm able to explain more in details the problem:
Every operation is performed by keeping Rosetta **active**:
- 1st dronekit connection always works
- 2nd dronekit connection sometimes works
- 3rd to 4-5th connection fails
- 5th to n-th connection fails, and Rosetta heartbeat becomes discontinuous (dronekit logs "No heartbeat in 5s/ link restored").

By stopping and re-launching Rosetta I'm able to connect successfully (we fall inside the 1st connection case).
Instead, when using SITL, same procedure, everything works (just to have a comparison).
I attempted to set wait_ready=False inside connect() and remove wait_ready('autopilot_version'), and connection always succeeds! Dronekit telemetry is always available by using this settings, the problem resides in dronekit commands: they sometimes work, sometimes are delayed, sometimes are not received at all!

**Comment by gab933** [comment]
Hi,
I've further investigated on connection problem:
by setting wait_ready=True is the same as setting wait_ready=['parameters', 'gps_0', 'armed', 'mode', 'attitude']).
By making some test, I can confirm that by omitting 'parameters' field connection immediately establishes. Therefore, more the connections we establish (keeping Rosetta **up**) more the time Rosetta uses to send parameters, ending on connection timeout!
Even if we omit 'parameters' field and therefore by establish a rapid connection, commands sent to Rosetta are not received until parameters are correctly sent. Since the time for sending those parameters increases with the number of connections, commands sent to Rosetta are progressively delayed (I test a set_servo command has been processed after about 5 mins I sent it from dronekit).
Hope this can help,
Regards,

Gabriele

**Comment by The1only** [comment]
Ahhh. Ok... interesting, sending the parameters only take a sekund or two in my system.
I never checked if is sends it to old sockets.


Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by gab933** [comment]
I forgot to specify that I'm using work branch "version" of Rosetta, I don't know if there is some misalignment with respect to master branch.
Regards,

Gabriele

**Comment by gab933** [comment]
Hi, solved.
By reinstalling the app everything works as expected. Maybe the installation via Android Studio generated this issue, now I've exported the apk file on sd card.
Thank you,

Gabriele
