### ISSUE TITLE
Loading the same or any mission several times fails

### ISSUE THREAD

**Issue by The1only** [RosettaDrone/rosettadrone#69]
**Describe the bug**
We can load a pretty advanced mission, flying way beyond the line of sight, but if we try to load it again it fails.
Seems we are missing a flush mission or someting.

**To Reproduce**
1. Load any mission using QGC
2. Make a small change and load the mission again
3. See error

**Expected behavior**
This should not be a problem at all

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
Yes, I have observed this issue. When we make a change in mission and upload it we get the error
`loadMission() returned error: The execution could not be executed (255)`
Please find the attached screenshot for the same

<img width="567" alt="image" src="https://user-images.githubusercontent.com/63089989/151389952-e8db7e66-49cb-41fa-926f-9841fcd6e7ff.png">

Please let me know if you have a fix for this. 
Thank You
@The1only

**Comment by kripper** [comment]
Please check latest version.
