### ISSUE TITLE
No GPS

### ISSUE THREAD

**Issue by droneslife** [RosettaDrone/rosettadrone#7]
Hello, are you receiving GPS on qgroundcontrol?

**Comment by The1only** [comment]
Yes….  Is there a problem?

**Comment by droneslife** [comment]
yes I see 0 GPS

**Comment by The1only** [comment]
Got 17 satellites, and I got velocity and position...
This is Mavic 2 Pro

I only uses the QGC 3.5.6 as the 4.x got crappy video…

**Comment by The1only** [comment]
You are outside right? Sorry just had to ask…

**Comment by droneslife** [comment]
yes I can see 16 sat on the cellphone but on the QGC no sat so maybe is the version I will change because video also crappy grey

**Comment by The1only** [comment]
Do you se 16 satellites in the Rosettadrone 2 software, ok 

And you got the right IP and PORT and the system says connected??

And you got a Mavic 2 Pro ?

**Comment by The1only** [comment]
Yea , the gray video is a problem. On the 3.5.6 the video got no gray problems and it has almost no latency.
There is something we need to understand there, as I get gray with my gStreamer also…

**Comment by The1only** [comment]
PS: I am in contact with the QGC guy’s to fix the video issue.

**Comment by droneslife** [comment]
im not on 3.5.6 and same grey color on the video

**Comment by droneslife** [comment]
oh ok after a while it looks better just some minutes

**Comment by The1only** [comment]
You got video issues on 3.5.6 ???

**Comment by droneslife** [comment]
what do you use on video bitrate and video encoding speed?

**Comment by The1only** [comment]
I do not transkode, just forward from DJI, the speed you can sett in the Rosettadrone app.
Might be I should transcode using gStreamer. The code is there, I just dont whant the added delay.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by The1only** [comment]
They say we should use QGC 4.05, for the video issue, it’s a bug and they will backport.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by droneslife** [comment]
ok! thx I will try again, Sr what is the file on the project where you add more flight modes and joystick?

**Comment by The1only** [comment]
DroneModel is the file that does all that. Together with MavlinkReceiver ...

Let me know if you make something we all may need.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by The1only** [comment]
PS: Joystick you add on the QGC, you can then fly with a Joystick connected to the PC, this is already implemented. Also reading the DJI controller stick on the QGC/Dronekit  is implemented.

**Comment by droneslife** [comment]
Thanks!! other question is the geo fence working?

**Comment by The1only** [comment]
Not tested, but is should.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by kripper** [comment]
Sometimes it's hard to init the GPS. Not related to Rosetta.
