### ISSUE TITLE
Crash when switch to main activity

### ISSUE THREAD

**Issue by danielwang628** [RosettaDrone/rosettadrone#70]
Sorry, I'm new for android studio.
 
Windows 10
Android studio 3.6 and 4.0
Huawei p30
DJI mavic mini .

When try to open main activity ,it was closed return to connection activity. 
In test mode was the same. 
Do you have any idea?

If open activity-gui.xml as design mode, there are some error like:

A <fragment> tag allows a layout file to dynamically include different layouts at runtime. At layout editing time the specific layout to be used is not known. You can choose which layout you would like previewed while editing the layout.
- <fragment com.google.android.gms.maps.SupportMapFragment ...> (Pick Layout...)
 Do not warn about <fragment> tags in this session

The following classes could not be instantiated:
- dji.ux.widget.ManualFocusWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.RemainingFlightTimeWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.internal.exposure.CameraExposureModeSettingWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.ReturnHomeWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.panel.PreFlightCheckListPanel (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.AutoExposureLockWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.controls.CameraCaptureWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.internal.exposure.CameraISOAndEISettingWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.TakeOffWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.panel.CameraSettingExposurePanel (Open Class, Show Exception, Clear Cache)
- dji.ux.internal.exposure.CameraApertureSettingWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.VisionWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.BatteryWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.internal.exposure.CameraShutterSettingWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.FocusExposureSwitchWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.panel.CameraSettingAdvancedPanel (Open Class, Show Exception, Clear Cache)
- dji.ux.internal.exposure.CameraEVSettingWidget (Open Class, Show Exception, Clear Cache)
- dji.ux.widget.FocusModeWidget (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.

**Comment by kripper** [comment]
Probably fixed.
