### ISSUE TITLE
Error in Android APK

### ISSUE THREAD

**Issue by cepoya** [RosettaDrone/rosettadrone#71]
After compile in android studio and create apk file.
the drone joystick already connected with mobile phone (i used huawei mate pro 20) and vehicle already connected with joystick.
unfortunately, the mobile application (Rosetta drone 2) not working well (doesn't detect the joystick and vehicle)
![image](https://user-images.githubusercontent.com/62041698/118449941-dcb95480-b71d-11eb-82fd-8db79af089bb.png)

could anyone help my problem?
thanks

**Comment by The1only** [comment]
Did you shut down Go-4, you can only have one app controlling the drone.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by cepoya** [comment]
> Did you shut down Go-4, you can only have one app controlling the drone. Best regard Terje Nilsen 9Tek AS Norway
> […](#)
> On May 17, 2021, at 09:43, cepoya ***@***.***> wrote: ﻿ After compile in android studio and create apk file. the drone joystick already connected with mobile phone (i used huawei mate pro 20) and vehicle already connected with joystick. unfortunately, the mobile application (Rosetta drone 2) not working well (doesn't detect the joystick and vehicle) could anyone help my problem? thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

al

**Comment by cepoya** [comment]
> Did you shut down Go-4, you can only have one app controlling the drone. Best regard Terje Nilsen 9Tek AS Norway
> […](#)
> On May 17, 2021, at 09:43, cepoya ***@***.***> wrote: ﻿ After compile in android studio and create apk file. the drone joystick already connected with mobile phone (i used huawei mate pro 20) and vehicle already connected with joystick. unfortunately, the mobile application (Rosetta drone 2) not working well (doesn't detect the joystick and vehicle) could anyone help my problem? thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

DJI GO 4 already shutdown but Rosetta Drone 2 APK, still doesn't work

**Comment by cepoya** [comment]
<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/google_key" />


how i get google key?

**Comment by cepoya** [comment]
update--

already connected with drone (but the Model not available)
and the APK don't wanna show and restart the application in android

![image](https://user-images.githubusercontent.com/62041698/118630324-a00e5b80-b7f8-11eb-9d1e-ef16ccd0ef8b.png)

**Comment by cepoya** [comment]
https://user-images.githubusercontent.com/62041698/118914033-baf5e280-b954-11eb-85b7-20a7080ad192.mp4

still error, anyone can help me?

**Comment by cepoya** [comment]
after disable rotate display,
the application already run

**Comment by davidan208** [comment]
hi @cepoya,
Can you help me with the way to build on the Android studio.
I had initialized the git lfs, created new key.xml file with dji key and google map key, but when I tried to build, I got this problem.
![258056821-8f16cd8f-3fa4-4846-beab-af55cbc58844](https://github.com/RosettaDrone/rosettadrone/assets/37769067/f99ece2b-5939-4673-b8c2-e67c80d5f64d)
How did you overcome this problem, I downloaded the lastest version of Android Studio (Android Gradle 3.6.4 - Gradle 7.2) but it didn't work.
Thanks.
