### ISSUE TITLE
Video not shown [work branch]

### ISSUE THREAD

**Issue by hardway777** [RosettaDrone/rosettadrone#73]
Video not shown in videoframe. Only label "WAITING FOR VIDEO".  _[work branch]_
I try all options and ports. It not help.
I don't know where problem - in Rosetta or in QGroundControl.

**Comment by The1only** [comment]
Use netcat to dump the UDP stream to verify if Rosettadrone sends data.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by cepoya** [comment]
> Video not shown in videoframe. Only label "WAITING FOR VIDEO". _[work branch]_
> I try all options and ports. It not help.
> I don't know where problem - in Rosetta or in QGroundControl.

same with me, the video not show in qground control in my mobile and in my laptop

**Comment by Phillweston** [comment]
I have also encountered this situation several times, and the result of the later test is that after opening the QGC ground station and then opening the rosettadrone APP, you can see the video screen at the ground station.

**Comment by kripper** [comment]
See https://docs.google.com/document/d/1wR56Mvd2OsT82kxMOD7f_3-c6yJGBtLaT8LuVrmC5wI/edit#heading=h.q9mp6yjsfxe5
