### ISSUE TITLE
Problem with altitude display in QGC

### ISSUE THREAD

**Issue by cbayerlein** [RosettaDrone/rosettadrone#74]
**I edited this issue because originally, I reported two problems in one issue. Now I seperated them to make them clearer**

**Describe the bug**
There is a problem with the altitude display in conjunction with QGC on Rosetta Drone 2.

**To Reproduce**
1. Power on RC and drone.
2. Start RD2 on the smartphone click on Open
3. disable safe mode by clicking on the padlock icon and take off by clicking the icon in RD2 and confirming with the slider
4. Start QGC - RD2 connects to QGC successfully (connection announced and map is updated in QGC and GCS goes green in RD2)
5. Altimeter in QGC shows wrong altitude 

**Expected behavior**
Altimeter in QGC should be correct

**Comment by cbayerlein** [comment]
I just discovered that when I disable both the virtual joystick and the hardware joystick in QGC, the ever increasing altitude issue doesn't appear. Sorry, forgot to write down that I activated this.

However, the problem with incorrect altitute display in QGC still persists.

Also, having to disable the joysticks is suboptimal. That was actually my use case: due to my physical handicap, I use a special joystick that identifies itself as a game controller on the PC. I would also like to be able to control the drone with it.,

**Comment by The1only** [comment]
Yes this is know, but it is so easy to fix most of us just fix it and noone has ever pushed the fix.
Find elevation report and do the math.

I will fix this together with a loot of other fixes this summer, when things comes down. 
I am flying long (4.5KM +)  missions with DJI Mavic 2 Pro and QGC these days, works fine. But still a few bugs inn loading a mission several times etc.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by cbayerlein** [comment]
Thank you, Terje! I found the error in the code and fixed it with this commit:

https://github.com/cbayerlein/rosettadrone_mini2/commit/16f4c253bc5336e77d9e5e8d31a0cf143fdaa714

However, since the altitude is an integer, I can't see cm values in QGC. Is there a way to fix this?

**Comment by The1only** [comment]
Yes,


/**
 * This is the altitude above the home position. It resets on each change of the current home position.
 */
public float altitude_relative;


private void send_altitude() {
    msg_altitude msg = new msg_altitude();
    LocationCoordinate3D coord = djiAircraft.getFlightController().getState().getAircraftLocation();
    msg.altitude_relative = (float) (coord.getAltitude() ); //* 1000);
    m_alt = msg.altitude_relative;
    sendMessage(msg);
}

Inn the Mavlink message it is already a float…

**Comment by cbayerlein** [comment]
Great, thanks for the hint! Changed int to float in this commit:

https://github.com/cbayerlein/rosettadrone_mini2/commit/4526f9ee61c54f169e6d8c04afaebe013f3cc53c

**Comment by cepoya** [comment]
> **I edited this issue because originally, I reported two problems in one issue. Now I seperated them to make them clearer**
> 
> **Describe the bug**
> There is a problem with the altitude display in conjunction with QGC on Rosetta Drone 2.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Power on RC and drone.
> 2. Start RD2 on the smartphone click on Open
> 3. disable safe mode by clicking on the padlock icon and take off by clicking the icon in RD2 and confirming with the slider
> 4. Start QGC - RD2 connects to QGC successfully (connection announced and map is updated in QGC and GCS goes green in RD2)
> 5. Altimeter in QGC shows wrong altitude
> 
> **Expected behavior**
> Altimeter in QGC should be correct

can you give link the QGC master?
the drone can't communicate (can't connect and update firmware with QGC)
