### ISSUE TITLE
the unit of bitrate in VideoService

### ISSUE THREAD

**Issue by robbiedood** [RosettaDrone/rosettadrone#77]
Dear rosettadrone, 

In VideoService.java, there is a parameter mvideoBitrate set to 3000
Is the unit bps or kbps ?

Hope to hear your expertise.

**Comment by The1only** [comment]
The value 3000 is never used, it is set from the config. Default is 2mbit. However this only applays to some drone types, end even there it seems not to do much.

https://developer.dji.com/api-reference/android-api/BaseClasses/DJIVideoFeeder.html#djivideofeeder_settranscodingdatarate_inline 

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by lukelu520** [comment]
Thanks for your reply @The1only , then what's the bitrate used by rosettadrone for streaming to QGroundcontrol ?

**Comment by The1only** [comment]
Depends on drone.
Let us know when you find out.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by lukelu520** [comment]
We have i) Mavic mini and ii) Mavic Air 2  @The1only

**Comment by ghost** [comment]
Does the Video transfer not work if the `mVideoBitrate` and `mEncodeSpeed` are not configured according to the drone. If yes, are there any references to get these values for the particular drone?
@The1only @lukelu0520 

Thank You

Himanshu V
Vyorius Drone Pvt Ltd
Delhi, India

**Comment by kripper** [comment]
Yes, bit rate is completely ignored.
