### ISSUE TITLE
Maps shows no google services on smart controller

### ISSUE THREAD

**Issue by highfreq** [RosettaDrone/rosettadrone#82]
I have everything compiled and working, my only prob at the moment is the maps rectangle on the smart controller screen showing "Remote stream won't run without Google play services wich are not supported by your device".

Any solution to that? at least not showing rectangle.

thanks

**Comment by The1only** [comment]
You need a google maps account and a key for it to work.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
Thank you, i have a key that includes maps, how can i put it in the project to compile with support for maps?

**Comment by highfreq** [comment]
Never mind found it!!!!


Should have look a bit better :)

**Comment by The1only** [comment]
The key goes in the same file as the DJI key.
Do not have the name right now.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
In android studio should i see the smart controller as rm500  ??

**Comment by The1only** [comment]
YES

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
Don't know why but i am not able to see it anymore. I have debug enabled but it doesn't show in android studio. I tried to revoke usb permissions but it doesn't ask for them anymore on usb connection. Phone connects and can see in Studio, just problem with smart controller. Any hint?

**Comment by The1only** [comment]
Change the mode in the controller to «charge only» if that does not help change is back to «file mode»… this must be done while connected to the USB bus. Some times one must reboot everything.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
rebooting everything seems to have solved the prob, thanks

**Comment by highfreq** [comment]
I put my key in and now i get message "Rosetta Drone 2 won't run wothout google play services wich are not supported by your device". I get this buy running the app from android studio with device attached. 
If instead of smart controller i use my samsung s21 phone than i get maps showing.

**Comment by The1only** [comment]
Chinese device? 
Must have google.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
It is a dji smart controller

**Comment by highfreq** [comment]
Solved it installing google services, now i have playstore too :)

Only problem left i get no video neither on the smart controller nor on the pc ground station, telemetry connects.

**Comment by The1only** [comment]
Yes Chinese, no Google… you must add Google manually. Get the .apk online.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by The1only** [comment]
What drone are you using? And what compiler tool version? 

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
Mavic pro 2. I installed Google services and all good on maps now.

Please let me know where to look for all info on android studio. Actually i think an update i made to android studio broke rosetta video.

**Comment by highfreq** [comment]
Android Studio 4.2.1 but maybe is gradle but i don't know where to look

**Comment by highfreq** [comment]
In File->project structure->project:

Gradle plugin 4.2.1
Gradle version 6.7.1

Just to make sure you understood my problem, i don't see video even inside rosetta drone on smart controller, just grey smart controller video.

**Comment by The1only** [comment]
Yes you can NOT update, no one have had time to figgure out why.!

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
So what can i do to fix it?

Should i use different gradle and plugin?

**Comment by The1only** [comment]
You need 6.3.x

We do not know why, needs to be debugged.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
I selected gradle 6.3 in project and tried to build but it says minimum version supported 6.7.1
Would you be so nice to tell me if and what i need to select to compile?
thank you very much for your patience

**Comment by The1only** [comment]
Was it the pluggin that needs to be 3.6? 
Check out in a new catalog and verify the origional files.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by highfreq** [comment]
I don't know how to do it. Is there a simple way of telling me what plugin and gradle to use?

**Comment by highfreq** [comment]
i downloaded project again and compiled, now it works.

Plugin 3.6.4
gradle version 6.7.1
