### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by highfreq** [RosettaDrone/rosettadrone#83]
Not much activity here lately, is the project dead?

**Comment by The1only** [comment]
I work in a sepperat thread for now, got som hard deadlines befor summer, will get back and clean up several issues in Juli. 
But please make requests and they will be prioritises and handled. 
Also DJI still have not released Mini 2 support yet so the only solution is the hack that is nice but a bit on the edge.
>

**Comment by BkMak16** [comment]
No we're here. I'm sure just unfortunately busy elsewhere for now.

**Comment by kripper** [comment]
100% alive again.
