### ISSUE TITLE
resource string/google_key not found

### ISSUE THREAD

**Issue by poett1** [RosettaDrone/rosettadrone#84]
Hello,
Android Stuido throws this error while building:
\path\to\rosettadrone\app\src\main\AndroidManifest.xml:116:9-118:50: AAPT: error: resource string/google_key (aka sq.rogue.rosettadrone:string/google_key) not found.

I'm new to Android Development. Is there anything missing?
I already tried the fix mentioned in [issue 67](https://github.com/The1only/rosettadrone/issues/67) , but nothing changed.

**Comment by The1only** [comment]
You have not added your google map key.
Go to google map development and get your key and add it to the key file.

**Comment by highfreq** [comment]
https://github.com/The1only/rosettadrone/issues/55#issuecomment-804831763
