### ISSUE TITLE
Smart controller video feed hangs

### ISSUE THREAD

**Issue by highfreq** [RosettaDrone/rosettadrone#85]
Opening the app for the first time video is sent correctl to the rtp endpoint. If the app is closed and reopened video doesn't work. Need to go into app and force terminate app. After forced terminating and restart it sends rtp video again.
Looks like rtp pipe hangs on closing.
This is on smart controller with mavic 2, compiled and downloaded yesterday from master

**Comment by gab933** [comment]
Hi,
I'm attempting to open the rtp streaming on vlc by means rtp://IP:port but it fails. How can you visualize rtp stream?
Thank you

**Comment by kripper** [comment]
See https://github.com/RosettaDrone/rosettadrone/issues/131
