### ISSUE TITLE
App Crash Phantom 4 need help

### ISSUE THREAD

**Issue by roland171993** [RosettaDrone/rosettadrone#86]
Mac Big Sur 
Android Studio 4.2

Smart phone: Infinix Hot 8 [](url)https://phonesdata.com/fr/smartphones/infinix/hot-8-5458286/
                        2 Go Ram
App crash when i press open button. please help

1-Install
2-launch app
3-Wait register Succes
4-Press OPEN button

Error :
java.lang.NoSuchMethodError: no non-static method "Lsq/rogue/rosettadrone/video/NativeHelper;.onFrameDataRecv([BIIZII)V"
        at sq.rogue.rosettadrone.video.NativeHelper.init(Native Method)
        at sq.rogue.rosettadrone.video.VideoService.b(:108)
        at sq.rogue.rosettadrone.video.VideoService.onCreate(:51)

<img width="925" alt="Screenshot 2021-07-12 at 13 06 15" src="https://user-images.githubusercontent.com/35685379/125303661-7c5d2280-e31c-11eb-95cb-de13cd0ede83.png">
<img width="995" alt="Screenshot 2021-07-12 at 13 07 28" src="https://user-images.githubusercontent.com/35685379/125303757-8ed75c00-e31c-11eb-95f3-017f00a9d297.png">

at Line 108 Detail:
<img width="625" alt="Screenshot 2021-07-12 at 14 22 55" src="https://user-images.githubusercontent.com/35685379/125304021-c2b28180-e31c-11eb-80a9-fe62855c4da7.png">

Thanks

**Comment by kripper** [comment]
Please check latest version and reopen if necessary.
