### ISSUE TITLE
Where to find the list of MAVLINK msgs supported and publishing frequency

### ISSUE THREAD

**Issue by frontw** [RosettaDrone/rosettadrone#91]
Hi! 

I just found this interesting project and trying to understand the possibility of its usage for drone control to fly along a given trajectory with ROS from PC.

Where could I get the list of data I could obtain? Could I get the position, orientation, linear and angular velocity?
What is the frequency of this data? Could it be 50 Hz or something like this?
How I could control the drone?

Thanks a lot!

**Comment by frontw** [comment]
Looks like I could find whar rosettadrone receives and sends in app/src/main/java/sq/rogue/rosettadrone/MAVLinkReceiver.java and app/src/main/java/sq/rogue/rosettadrone/DroneModel.java
Am I right that maximum frequency is 10Hz? (according to `void tick() { // Called ever 100ms...`)?

**Comment by The1only** [comment]
Yes,  can be changed if you need faster updates, but it is a CPU tradeoff.

**Comment by frontw** [comment]
Thanks for answering!
According to your practice, does Mobile SDK itself let to get new data at a frequency around 50 Hz?

**Comment by The1only** [comment]
I did not try but it can be set.
However I fly using computer vision AI in a PC on the ground and Dronekit as a controller all the time, and 10Hz is no problem, remember the drone is actually flying, all you need to to correct it’s heading/altitude/direction etc.
Unless you whant to fly very fast, then 50Hz make sense.

**Comment by kripper** [comment]
Check the code. Search for "MAV_"
